### PR TITLE
TIDAL (tidalhifi.com) resolver

### PR DESCRIPTION
**Pull request by theli-ua**
Same code should also work for WIMP.com but Its not available here in US so I did not add support for both
Can be configured to get stream urls from low 64k AAC to lossless flacs

### CODE REVIEW

**Comment by muesli** [comment]
Awesome!

**Comment by muesli** [comment]
@dschmidt I rest assured you're gonna review? :-)

**Comment by jherskowitz** [comment]
I got a higher rez icon for it... https://www.dropbox.com/s/9paaiwrpixv7rqt/icon.png?dl=0

**Comment by jherskowitz** [comment]
Should drag/drop support of service links (e.g. tidalhifi.com/track/1186619) be in the resolver or somewhere else?

**Comment by willstott101** [comment]
Awesome. Very glad someone got this to work. Looks like it was just the API token that was stopping mine from working... that's really frustrating. I took it from the web player. Might I ask where I got yours?

**Comment by theli-ua** [comment]
@willstott101 android app, mitm

**Comment by willstott101** [comment]
Sigh, my nokia brick lets me down once again. Could have tried with my iPad I guess. Thanks for this. Are you planning on doing collection support? (I'll do it otherwise)

**Comment by theli-ua** [comment]
@willstott101 I'm not really familliar with js and I'd be glad if someone else would do it instead of me.

**Comment by willstott101** [comment]
@theli-ua Fair enough. I'll fork your fork after I have dinner.

**Comment by dschmidt** [comment]
@muesli of course, I want to :-) just missed the request so far.

It looks decent, @willstott101 is going to port it to our new API, that will make me completely happy and ready to merge :+1:

**Comment by theli-ua** [comment]
Artist/Playlist/Album url resolution works for me now

**Pull request merged**
