### PR TITLE
Refactor youtube resolver a bit and parse out Track - Artist out of g…

### PR DESCRIPTION
**Pull request by theli-ua**
…oogle's generated description for first result in search query when resolving

### CODE REVIEW

**Comment by mrmaffen** [comment]
Just tried installing it in tomahawk-android. Couple of issues occurred:
- https://github.com/tomahawk-player/tomahawk-resolvers/pull/84/files#diff-359b2a7bdc8532eedcd193bcf08f2cc9R1009 should be this.getCandidates
- https://github.com/tomahawk-player/tomahawk-resolvers/pull/84/files#diff-359b2a7bdc8532eedcd193bcf08f2cc9R691 apiQuery is a local variable that is never being used
- https://github.com/tomahawk-player/tomahawk-resolvers/pull/84/files#diff-359b2a7bdc8532eedcd193bcf08f2cc9R536 the regular expression is incorrect. This charset "[=\+-\s]" should be "[=\+\-\s]" or "[=\+\s-]. Otherwise the hyphen would make this a char range from \+ to \s. Which obviously doesn't work with character classes like \s.

After resolving those issues and trying to search for the keyword "James Blake" I got this log output: 
```
log: youtube_1446232594372: YouTube debug: Bad result from track lookup? http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=b14d61bf2f7968731eb686c7b4a1516e&format=json&limit=5&artist=James%20Blake&track=NPR%20MUSIC%20FRONT%20ROW: {"error":6,"message":"Track not found","links":[]}
```
Any ideas on what might be the issue here?

**Comment by mrmaffen** [comment]
A few more notes:
- The code style seems a little off. Some lines are over 250 characters long. There are redundant and missing commas and semicolons. Some variables and functions are not being used. All internally used functions' names should start with an underscore.

- Why are you constructing RegExp objects without using "new" ?

- In the parseURLS-function there's a possibly problematic use of the variable "itag" because it's being accessed from within a nested function. The same applies to the variable "js_player_url".

- Throughout the script you are passing URLs with parameters to Tomahawk.get. Those parameters should be passed to Tomahawk.get in the settings object. (see https://github.com/tomahawk-player/tomahawk-resolvers/blob/master/soundcloud/content/contents/code/soundcloud.js#L119)

- The iso8601toSeconds-function should be replaced by a simple call to ```new Date(isoString).getTime();```

Most of these issues appeared as highlighted when I was looking at the code in IntelliJ. I can give you a license key for the ultimate version if you are interested in trying it out yourself.

**Comment by theli-ua** [comment]
>Why are you constructing RegExp objects without using "new" ?
The only regexps I added are being constructed with a new.
>Throughout the script you are passing URLs with parameters to Tomahawk.get.
I pass them in a settings object as you showed, I did not change the ones which were already there
>The iso8601toSeconds-function should be replaced by a simple call to new Date(isoString).getTime();
You are welcome to make this change :), I tried to change as little as I could
>apiQuery is a local global variable that is never being used
That is an actuall bug I introduced, yeah, should happen on hatchet only though, thus I never noticed
>"[=+-\s]"
That is an incorrect range indeed, I wonder why does this even work for me on desktop

>Most of these issues appeared as highlighted when I was looking at the code in IntelliJ. I can give you a license key for the ultimate version if you are interested in trying it out yourself.
Thank you but I'm good. I also bought a key for an IntelliJ for w/e reason, never used it since then :-/

**Comment by mrmaffen** [comment]
merged

**Pull request closed without merging**
