### PR TITLE
Add resolver for kibergrad.com

### PR DESCRIPTION
**Pull request by theli-ua**

### CODE REVIEW

**Comment by mrmaffen** [comment]
Please move the LRUCache stuff into a separate script and link to it via metadata.json.
Other than that I think that this PR can be merged.

**Comment by mrmaffen** [comment]
Please also add an iconBackground.png and an iconWhite.png to the images folder and link to it in metadata.json. Refer to https://github.com/tomahawk-player/tomahawk-resolvers/blob/9eea07614e6ca682c71edc5ea16f03246b7eaa69/soundcloud/content/metadata.json#L21-21

**Comment by theli-ua** [comment]
wrt icons: sorry, I'm not an artist

**Comment by mrmaffen** [comment]
https://drive.google.com/file/d/0B0OEIHngt2GhZVRhMnpjMHpOOVk/view?usp=sharing

**Pull request merged**
